name: test

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: yarn install

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test
